// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: orion/v1/jobs.proto

package orionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobService_SubmitJob_FullMethodName     = "/orion.v1.JobService/SubmitJob"
	JobService_GetJob_FullMethodName        = "/orion.v1.JobService/GetJob"
	JobService_WatchJob_FullMethodName      = "/orion.v1.JobService/WatchJob"
	JobService_WatchPipeline_FullMethodName = "/orion.v1.JobService/WatchPipeline"
)

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobService is the primary gRPC service for Orion.
// It exposes both unary RPCs (equivalent to the HTTP API) and server-streaming
// RPCs for real-time job and pipeline event delivery.
type JobServiceClient interface {
	// SubmitJob creates a new job. Equivalent to POST /jobs.
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*Job, error)
	// GetJob retrieves a job by ID. Equivalent to GET /jobs/{id}.
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*Job, error)
	// WatchJob opens a server-streaming connection that receives one JobEvent
	// for every status transition until the job reaches a terminal state
	// (completed, dead, cancelled). The stream closes automatically at terminal.
	WatchJob(ctx context.Context, in *WatchJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	// WatchPipeline opens a server-streaming connection for a pipeline.
	// Receives one PipelineEvent for every pipeline status change.
	// Stream closes when the pipeline reaches a terminal state.
	WatchPipeline(ctx context.Context, in *WatchPipelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PipelineEvent], error)
}

type jobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobServiceClient(cc grpc.ClientConnInterface) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, JobService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, JobService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) WatchJob(ctx context.Context, in *WatchJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobService_ServiceDesc.Streams[0], JobService_WatchJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchJobRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobService_WatchJobClient = grpc.ServerStreamingClient[JobEvent]

func (c *jobServiceClient) WatchPipeline(ctx context.Context, in *WatchPipelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PipelineEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobService_ServiceDesc.Streams[1], JobService_WatchPipeline_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPipelineRequest, PipelineEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobService_WatchPipelineClient = grpc.ServerStreamingClient[PipelineEvent]

// JobServiceServer is the server API for JobService service.
// All implementations must embed UnimplementedJobServiceServer
// for forward compatibility.
//
// JobService is the primary gRPC service for Orion.
// It exposes both unary RPCs (equivalent to the HTTP API) and server-streaming
// RPCs for real-time job and pipeline event delivery.
type JobServiceServer interface {
	// SubmitJob creates a new job. Equivalent to POST /jobs.
	SubmitJob(context.Context, *SubmitJobRequest) (*Job, error)
	// GetJob retrieves a job by ID. Equivalent to GET /jobs/{id}.
	GetJob(context.Context, *GetJobRequest) (*Job, error)
	// WatchJob opens a server-streaming connection that receives one JobEvent
	// for every status transition until the job reaches a terminal state
	// (completed, dead, cancelled). The stream closes automatically at terminal.
	WatchJob(*WatchJobRequest, grpc.ServerStreamingServer[JobEvent]) error
	// WatchPipeline opens a server-streaming connection for a pipeline.
	// Receives one PipelineEvent for every pipeline status change.
	// Stream closes when the pipeline reaches a terminal state.
	WatchPipeline(*WatchPipelineRequest, grpc.ServerStreamingServer[PipelineEvent]) error
	mustEmbedUnimplementedJobServiceServer()
}

// UnimplementedJobServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobServiceServer struct{}

func (UnimplementedJobServiceServer) SubmitJob(context.Context, *SubmitJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedJobServiceServer) GetJob(context.Context, *GetJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedJobServiceServer) WatchJob(*WatchJobRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchJob not implemented")
}
func (UnimplementedJobServiceServer) WatchPipeline(*WatchPipelineRequest, grpc.ServerStreamingServer[PipelineEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchPipeline not implemented")
}
func (UnimplementedJobServiceServer) mustEmbedUnimplementedJobServiceServer() {}
func (UnimplementedJobServiceServer) testEmbeddedByValue()                    {}

// UnsafeJobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobServiceServer will
// result in compilation errors.
type UnsafeJobServiceServer interface {
	mustEmbedUnimplementedJobServiceServer()
}

func RegisterJobServiceServer(s grpc.ServiceRegistrar, srv JobServiceServer) {
	// If the following call panics, it indicates UnimplementedJobServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobService_ServiceDesc, srv)
}

func _JobService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_WatchJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobServiceServer).WatchJob(m, &grpc.GenericServerStream[WatchJobRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobService_WatchJobServer = grpc.ServerStreamingServer[JobEvent]

func _JobService_WatchPipeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPipelineRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobServiceServer).WatchPipeline(m, &grpc.GenericServerStream[WatchPipelineRequest, PipelineEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobService_WatchPipelineServer = grpc.ServerStreamingServer[PipelineEvent]

// JobService_ServiceDesc is the grpc.ServiceDesc for JobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orion.v1.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _JobService_SubmitJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _JobService_GetJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchJob",
			Handler:       _JobService_WatchJob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchPipeline",
			Handler:       _JobService_WatchPipeline_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orion/v1/jobs.proto",
}
