// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orion/v1/jobs.proto

package orionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                // human-readable job name
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                // "inline" or "k8s_job"
	QueueName      string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`     // "high", "default", "low"
	Priority       int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`                       // 1-10, default 5
	MaxRetries     int32                  `protobuf:"varint,5,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"` // default 3
	Payload        *JobPayload            `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // optional: prevents duplicate submissions
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_orion_v1_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_orion_v1_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitJobRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubmitJobRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *SubmitJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitJobRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *SubmitJobRequest) GetPayload() *JobPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubmitJobRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // UUID of the job
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_orion_v1_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_orion_v1_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WatchJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // UUID of the job to watch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchJobRequest) Reset() {
	*x = WatchJobRequest{}
	mi := &file_orion_v1_jobs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchJobRequest) ProtoMessage() {}

func (x *WatchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_jobs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchJobRequest.ProtoReflect.Descriptor instead.
func (*WatchJobRequest) Descriptor() ([]byte, []int) {
	return file_orion_v1_jobs_proto_rawDescGZIP(), []int{2}
}

func (x *WatchJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WatchPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"` // UUID of the pipeline to watch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPipelineRequest) Reset() {
	*x = WatchPipelineRequest{}
	mi := &file_orion_v1_jobs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPipelineRequest) ProtoMessage() {}

func (x *WatchPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_jobs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPipelineRequest.ProtoReflect.Descriptor instead.
func (*WatchPipelineRequest) Descriptor() ([]byte, []int) {
	return file_orion_v1_jobs_proto_rawDescGZIP(), []int{3}
}

func (x *WatchPipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	QueueName     string                 `protobuf:"bytes,5,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Attempt       int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,8,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	WorkerId      string                 `protobuf:"bytes,9,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Payload       *JobPayload            `protobuf:"bytes,14,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_orion_v1_jobs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_jobs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_orion_v1_jobs_proto_rawDescGZIP(), []int{4}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Job) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Job) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Job) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Job) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Job) GetPayload() *JobPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type JobPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HandlerName    string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`                                          // for inline jobs
	Args           map[string]string      `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // handler arguments
	KubernetesSpec *KubernetesSpec        `protobuf:"bytes,3,opt,name=kubernetes_spec,json=kubernetesSpec,proto3" json:"kubernetes_spec,omitempty"`                                 // for k8s_job type
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobPayload) Reset() {
	*x = JobPayload{}
	mi := &file_orion_v1_jobs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPayload) ProtoMessage() {}

func (x *JobPayload) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_jobs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobPayload.ProtoReflect.Descriptor instead.
func (*JobPayload) Descriptor() ([]byte, []int) {
	return file_orion_v1_jobs_proto_rawDescGZIP(), []int{5}
}

func (x *JobPayload) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *JobPayload) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *JobPayload) GetKubernetesSpec() *KubernetesSpec {
	if x != nil {
		return x.KubernetesSpec
	}
	return nil
}

type KubernetesSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Image          string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command        []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	EnvVars        map[string]string      `protobuf:"bytes,4,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Namespace      string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Resources      *ResourceRequest       `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	ServiceAccount string                 `protobuf:"bytes,7,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	TtlSeconds     int32                  `protobuf:"varint,8,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KubernetesSpec) Reset() {
	*x = KubernetesSpec{}
	mi := &file_orion_v1_jobs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesSpec) ProtoMessage() {}

func (x *KubernetesSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_jobs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesSpec.ProtoReflect.Descriptor instead.
func (*KubernetesSpec) Descriptor() ([]byte, []int) {
	return file_orion_v1_jobs_proto_rawDescGZIP(), []int{6}
}

func (x *KubernetesSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *KubernetesSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *KubernetesSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *KubernetesSpec) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *KubernetesSpec) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesSpec) GetResources() *ResourceRequest {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *KubernetesSpec) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

func (x *KubernetesSpec) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type ResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`       // e.g. "4" or "500m"
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"` // e.g. "16Gi"
	Gpu           int32                  `protobuf:"varint,3,opt,name=gpu,proto3" json:"gpu,omitempty"`      // nvidia.com/gpu count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	mi := &file_orion_v1_jobs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_jobs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_orion_v1_jobs_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceRequest) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceRequest) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ResourceRequest) GetGpu() int32 {
	if x != nil {
		return x.Gpu
	}
	return 0
}

type JobEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName        string                 `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	PreviousStatus string                 `protobuf:"bytes,3,opt,name=previous_status,json=previousStatus,proto3" json:"previous_status,omitempty"`
	NewStatus      string                 `protobuf:"bytes,4,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	WorkerId       string                 `protobuf:"bytes,5,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Attempt        int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobEvent) Reset() {
	*x = JobEvent{}
	mi := &file_orion_v1_jobs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEvent) ProtoMessage() {}

func (x *JobEvent) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_jobs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEvent.ProtoReflect.Descriptor instead.
func (*JobEvent) Descriptor() ([]byte, []int) {
	return file_orion_v1_jobs_proto_rawDescGZIP(), []int{8}
}

func (x *JobEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobEvent) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobEvent) GetPreviousStatus() string {
	if x != nil {
		return x.PreviousStatus
	}
	return ""
}

func (x *JobEvent) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *JobEvent) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobEvent) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *JobEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type PipelineEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PipelineId     string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	PipelineName   string                 `protobuf:"bytes,2,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"`
	NodeId         string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                         // which node changed (empty = overall)
	NodeStatus     string                 `protobuf:"bytes,4,opt,name=node_status,json=nodeStatus,proto3" json:"node_status,omitempty"`             // new status of that node
	PipelineStatus string                 `protobuf:"bytes,5,opt,name=pipeline_status,json=pipelineStatus,proto3" json:"pipeline_status,omitempty"` // overall pipeline status
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PipelineEvent) Reset() {
	*x = PipelineEvent{}
	mi := &file_orion_v1_jobs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineEvent) ProtoMessage() {}

func (x *PipelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_orion_v1_jobs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineEvent.ProtoReflect.Descriptor instead.
func (*PipelineEvent) Descriptor() ([]byte, []int) {
	return file_orion_v1_jobs_proto_rawDescGZIP(), []int{9}
}

func (x *PipelineEvent) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineEvent) GetPipelineName() string {
	if x != nil {
		return x.PipelineName
	}
	return ""
}

func (x *PipelineEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PipelineEvent) GetNodeStatus() string {
	if x != nil {
		return x.NodeStatus
	}
	return ""
}

func (x *PipelineEvent) GetPipelineStatus() string {
	if x != nil {
		return x.PipelineStatus
	}
	return ""
}

func (x *PipelineEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_orion_v1_jobs_proto protoreflect.FileDescriptor

const file_orion_v1_jobs_proto_rawDesc = "" +
	"\n" +
	"\x13orion/v1/jobs.proto\x12\borion.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x01\n" +
	"\x10SubmitJobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\x05 \x01(\x05R\n" +
	"maxRetries\x12.\n" +
	"\apayload\x18\x06 \x01(\v2\x14.orion.v1.JobPayloadR\apayload\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"(\n" +
	"\x0fWatchJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"7\n" +
	"\x14WatchPipelineRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\"\xf9\x03\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x05 \x01(\tR\tqueueName\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12\x1f\n" +
	"\vmax_retries\x18\b \x01(\x05R\n" +
	"maxRetries\x12\x1b\n" +
	"\tworker_id\x18\t \x01(\tR\bworkerId\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fcompleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12.\n" +
	"\apayload\x18\x0e \x01(\v2\x14.orion.v1.JobPayloadR\apayload\"\xdf\x01\n" +
	"\n" +
	"JobPayload\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\x122\n" +
	"\x04args\x18\x02 \x03(\v2\x1e.orion.v1.JobPayload.ArgsEntryR\x04args\x12A\n" +
	"\x0fkubernetes_spec\x18\x03 \x01(\v2\x18.orion.v1.KubernetesSpecR\x0ekubernetesSpec\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x02\n" +
	"\x0eKubernetesSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12@\n" +
	"\benv_vars\x18\x04 \x03(\v2%.orion.v1.KubernetesSpec.EnvVarsEntryR\aenvVars\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x127\n" +
	"\tresources\x18\x06 \x01(\v2\x19.orion.v1.ResourceRequestR\tresources\x12'\n" +
	"\x0fservice_account\x18\a \x01(\tR\x0eserviceAccount\x12\x1f\n" +
	"\vttl_seconds\x18\b \x01(\x05R\n" +
	"ttlSeconds\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x0fResourceRequest\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\x12\x10\n" +
	"\x03gpu\x18\x03 \x01(\x05R\x03gpu\"\x9a\x02\n" +
	"\bJobEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x02 \x01(\tR\ajobName\x12'\n" +
	"\x0fprevious_status\x18\x03 \x01(\tR\x0epreviousStatus\x12\x1d\n" +
	"\n" +
	"new_status\x18\x04 \x01(\tR\tnewStatus\x12\x1b\n" +
	"\tworker_id\x18\x05 \x01(\tR\bworkerId\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xf2\x01\n" +
	"\rPipelineEvent\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12#\n" +
	"\rpipeline_name\x18\x02 \x01(\tR\fpipelineName\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vnode_status\x18\x04 \x01(\tR\n" +
	"nodeStatus\x12'\n" +
	"\x0fpipeline_status\x18\x05 \x01(\tR\x0epipelineStatus\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xff\x01\n" +
	"\n" +
	"JobService\x126\n" +
	"\tSubmitJob\x12\x1a.orion.v1.SubmitJobRequest\x1a\r.orion.v1.Job\x120\n" +
	"\x06GetJob\x12\x17.orion.v1.GetJobRequest\x1a\r.orion.v1.Job\x12;\n" +
	"\bWatchJob\x12\x19.orion.v1.WatchJobRequest\x1a\x12.orion.v1.JobEvent0\x01\x12J\n" +
	"\rWatchPipeline\x12\x1e.orion.v1.WatchPipelineRequest\x1a\x17.orion.v1.PipelineEvent0\x01B:Z8github.com/shreeharshshinde/orion/proto/orion/v1;orionv1b\x06proto3"

var (
	file_orion_v1_jobs_proto_rawDescOnce sync.Once
	file_orion_v1_jobs_proto_rawDescData []byte
)

func file_orion_v1_jobs_proto_rawDescGZIP() []byte {
	file_orion_v1_jobs_proto_rawDescOnce.Do(func() {
		file_orion_v1_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orion_v1_jobs_proto_rawDesc), len(file_orion_v1_jobs_proto_rawDesc)))
	})
	return file_orion_v1_jobs_proto_rawDescData
}

var file_orion_v1_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_orion_v1_jobs_proto_goTypes = []any{
	(*SubmitJobRequest)(nil),      // 0: orion.v1.SubmitJobRequest
	(*GetJobRequest)(nil),         // 1: orion.v1.GetJobRequest
	(*WatchJobRequest)(nil),       // 2: orion.v1.WatchJobRequest
	(*WatchPipelineRequest)(nil),  // 3: orion.v1.WatchPipelineRequest
	(*Job)(nil),                   // 4: orion.v1.Job
	(*JobPayload)(nil),            // 5: orion.v1.JobPayload
	(*KubernetesSpec)(nil),        // 6: orion.v1.KubernetesSpec
	(*ResourceRequest)(nil),       // 7: orion.v1.ResourceRequest
	(*JobEvent)(nil),              // 8: orion.v1.JobEvent
	(*PipelineEvent)(nil),         // 9: orion.v1.PipelineEvent
	nil,                           // 10: orion.v1.JobPayload.ArgsEntry
	nil,                           // 11: orion.v1.KubernetesSpec.EnvVarsEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_orion_v1_jobs_proto_depIdxs = []int32{
	5,  // 0: orion.v1.SubmitJobRequest.payload:type_name -> orion.v1.JobPayload
	12, // 1: orion.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: orion.v1.Job.updated_at:type_name -> google.protobuf.Timestamp
	12, // 3: orion.v1.Job.completed_at:type_name -> google.protobuf.Timestamp
	5,  // 4: orion.v1.Job.payload:type_name -> orion.v1.JobPayload
	10, // 5: orion.v1.JobPayload.args:type_name -> orion.v1.JobPayload.ArgsEntry
	6,  // 6: orion.v1.JobPayload.kubernetes_spec:type_name -> orion.v1.KubernetesSpec
	11, // 7: orion.v1.KubernetesSpec.env_vars:type_name -> orion.v1.KubernetesSpec.EnvVarsEntry
	7,  // 8: orion.v1.KubernetesSpec.resources:type_name -> orion.v1.ResourceRequest
	12, // 9: orion.v1.JobEvent.timestamp:type_name -> google.protobuf.Timestamp
	12, // 10: orion.v1.PipelineEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 11: orion.v1.JobService.SubmitJob:input_type -> orion.v1.SubmitJobRequest
	1,  // 12: orion.v1.JobService.GetJob:input_type -> orion.v1.GetJobRequest
	2,  // 13: orion.v1.JobService.WatchJob:input_type -> orion.v1.WatchJobRequest
	3,  // 14: orion.v1.JobService.WatchPipeline:input_type -> orion.v1.WatchPipelineRequest
	4,  // 15: orion.v1.JobService.SubmitJob:output_type -> orion.v1.Job
	4,  // 16: orion.v1.JobService.GetJob:output_type -> orion.v1.Job
	8,  // 17: orion.v1.JobService.WatchJob:output_type -> orion.v1.JobEvent
	9,  // 18: orion.v1.JobService.WatchPipeline:output_type -> orion.v1.PipelineEvent
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_orion_v1_jobs_proto_init() }
func file_orion_v1_jobs_proto_init() {
	if File_orion_v1_jobs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orion_v1_jobs_proto_rawDesc), len(file_orion_v1_jobs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orion_v1_jobs_proto_goTypes,
		DependencyIndexes: file_orion_v1_jobs_proto_depIdxs,
		MessageInfos:      file_orion_v1_jobs_proto_msgTypes,
	}.Build()
	File_orion_v1_jobs_proto = out.File
	file_orion_v1_jobs_proto_goTypes = nil
	file_orion_v1_jobs_proto_depIdxs = nil
}
